Sign-in view
adshayanB/ECE452 pull request #8
Opened 2023-06-21 01:02 UTC by adshayanB

![image](https://github.com/adshayanB/ECE452/assets/41243143/06189a3d-decd-4174-b9c8-c9758f2291b2)

2023-06-21 15:10 UTC, RishanR requested changes

2023-06-21 16:26 UTC, RishanR commented on app/src/main/java/com/example/farmeraid/sign_in/SignInViewModel.kt
> +                }
Sounds good

2023-06-22 23:51 UTC, RishanR commented on app/src/main/java/com/example/farmeraid/sign_in/SignInViewModel.kt
> +    userRepository: UserRepository
Change this to `private val userRepository: UserRepository`

2023-06-22 23:51 UTC, RishanR commented on app/src/main/java/com/example/farmeraid/sign_in/SignInViewModel.kt
> +    private val userRepository: UserRepository = userRepository;
You can get rid of this line with the above change

2023-06-22 23:52 UTC, RishanR commented on app/src/main/java/com/example/farmeraid/sign_in/views/SignInScreenView.kt
> +            onClick = { },
Add a TODO comment here so we know that we need to add the onClick for this later

2023-06-22 23:53 UTC, RishanR commented on app/src/main/java/com/example/farmeraid/sign_in/views/SignInScreenView.kt
> +            Button(
Use the ButtonView component in uiComponents

2023-06-22 23:54 UTC, RishanR requested changes
Just a few more requested changes above, but its looking good!

2023-06-23 02:12 UTC, adshayanB commented
Will use a similar format to implement the sign up screen once this pr is merged :)

2023-06-23 17:44 UTC, RishanR approved these changes
LGTM!

2023-06-23 17:46 UTC, merged